# Simple docker-compose for skipping part with symfony-cli or native project installation
version: '3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./sf:/var/www

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./sf:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/app.conf:/etc/nginx/sites-available/default.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    ports:
      - "${NGINX_PORT_HOST}:80"